#!/bin/sh

case "$ACTION" in
        add)
                [ -n "${DEVNAME}" ] && [ "${DEVNAME##usb/lp*}" = "" ] && {
                        
                        chmod 660 /dev/"$DEVNAME"
                        chgrp lp /dev/"$DEVNAME"
                        
                        PRINTERNAME=`cut -d: -f4 /sys/class/usbmisc/$DEVICENAME/device/ieee1284_id | sed -e 's/;.*//' | sed -e 's/ .*//'`
                        ln -s /dev/$DEVNAME /dev/$PRINTERNAME
                        mkdir /tmp/printers
                        echo "/dev/$PRINTERNAME" > /tmp/printers/$DEVICENAME
                }
                ;;
        remove)
                [ -n "${DEVNAME}" ] && [ "${DEVNAME##usb/lp*}" = "" ] && {
                        # device is gone
                        PRINTERNAME=`cat /tmp/printers/$DEVICENAME`
                        rm $PRINTERNAME
                        rm /tmp/printers/$DEVICENAME
                }
                ;;
esac
